-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-change-spoofuser-binary.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  spoofuser ALTER su_name TYPE TEXT;
ALTER TABLE  spoofuser ALTER su_normalized TYPE TEXT;