-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-change-spoofuser-su_legal.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX su_normname_idx;
CREATE TEMPORARY TABLE /*_*/__temp__spoofuser AS
SELECT  su_name,  su_normalized,  su_legal,  su_error
FROM  /*_*/spoofuser;
DROP  TABLE  /*_*/spoofuser;
CREATE TABLE  /*_*/spoofuser (    su_name VARCHAR(255) NOT NULL,    su_normalized VARCHAR(255) DEFAULT NULL,    su_legal SMALLINT DEFAULT NULL,    su_error CLOB DEFAULT NULL,    PRIMARY KEY(su_name)  );
INSERT INTO  /*_*/spoofuser (    su_name, su_normalized, su_legal,    su_error  )
SELECT  su_name,  su_normalized,  su_legal,  su_error
FROM  /*_*/__temp__spoofuser;
DROP  TABLE /*_*/__temp__spoofuser;
CREATE INDEX su_normname_idx ON  /*_*/spoofuser (su_normalized, su_name);