-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-change-spoofuser-binary.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/spoofuser
CHANGE  su_name su_name VARBINARY(255) NOT NULL,
CHANGE  su_normalized su_normalized VARBINARY(255) DEFAULT NULL;